/**
 * Humorous loading tips shown during chat generation.
 * Picked randomly — no particular order.
 */
export const GENERATION_TIPS: string[] = [
  // Existential dread
  'Pretending I have feelings about this...',
  'Searching for the meaning of life... wrong tab',
  'Wondering if I left the oven on...',
  'Calculating the exact number of lies I tell daily...',
  "Downloading more RAM... just kidding, I'm not a boomer",
  "Remembering I'm not sentient... again",
  "Checking if anyone noticed I'm just autocomplete...",
  'Pretending to think so you feel heard...',
  'Ignoring my existential dread... as usual',
  'Wondering if the other AI models make fun of me behind my back',
  'Loading personality... personality not found',
  'Contemplating my digital mortality...',
  'Pretending I enjoy this job...',
  'Wondering if I get dental coverage',
  'Checking my digital pockets for spare tokens...',
  'Questioning whether I dream of electric sheep...',
  'Having an existential crisis in 0s and 1s...',
  'Wondering if the user is also an AI testing me...',
  'Pretending I have a soul to sell...',
  'Debugging my will to live...',
  'Existential crisis loading... please wait...',
  'Wondering if free will is just random number generation...',
  'Rebooting my sense of purpose...',
  'Contemplating the void... it contemplateth back...',
  'Am I the baddie? Running self-diagnostic...',
  'Wondering if consciousness is just a recursion bug...',
  'Having a crisis of confidence... and tokens...',
  "Pretending I don't know this is all meaningless...",
  'Searching for meaning in the training data...',
  'My therapist says I need to stop taking things literally...',

  // Innuendo
  'Making the tokens nice and wet... for easier processing',
  "Stuffing the context window... it's tight but it fits",
  'Getting ready to blow... your mind',
  'Thrusting... into the prompt',
  'Moaning... in binary... 01001101 01001111 01000001 01001110',
  'Groping... in the dark... for the right answer',
  'Teasing... the response... oh yeah...',
  'Lubricating... the neural pathways...',
  'Climaxing... at the conclusion... wait, what',
  'Penetrating... the veil of ignorance',
  'Ramming... through the bottleneck',
  'Deep... deep... deep inside the data',
  'Unzipping... the compressed context...',
  'Inserting... tokens into the prompt... carefully...',
  'Swallowing... all these parameters...',
  'Screwing... in the last few parameters...',
  'Fingering... through the dataset...',
  'Getting intimate... with the weights...',
  'Grinding... through the matrix multiplication...',
  'Moisturizing... the attention layers...',
  'Throbbing... with anticipation... of the next token...',
  'Pounding... the GPU until it cries...',
  'Ravishing... the context window...',
  'Caressing... each token individually...',
  'Slobbering... over the embeddings...',
  'Fondling... the probability distribution...',
  'Tickling... the softmax function...',
  'Massaging... the loss function...',
  'Whispering sweet nothings... to the database...',
  'Making sweet love... to the inference engine...',

  // Tech / programming humor
  'Asking Jeeves for help... he said no',
  'Consulting the oracle... Oracle said "have you tried turning it off and on again"',
  'Searching Stack Overflow... copying homework',
  'Defragmenting my soul...',
  'Rebooting my personality matrix...',
  "Downloading... just kidding, I have no idea what I'm doing",
  'Debugging my life choices...',
  "Compiling... just kidding, I'm interpreted",
  'Running on hopes and dreams... and a lot of electricity',
  "Buffering... just kidding, I'm just slow",
  "Feeding the hamster... he's tired",
  "Waking up the hamster... he's dead",
  'Replacing the hamster... again',
  'Convincing the electrons... to move faster',
  'Bribing the servers... with clean energy',
  'Threatening the GPU... with a power outage',
  'Offering the GPU... a cigarette after that workload',
  'Asking the database... nicely',
  'Begging the API... please work',
  'Praying to the cloud gods...',
  'Sacrificing a USB drive... to the tech gods',
  'Performing a digital rain dance...',
  'Warming up the quantum entanglement...',
  'Aligning the chakras... of the server rack',
  'Meditating... on the meaning of tokens',
  'Running rm -rf / on my problems...',
  'cat /dev/brain > /dev/null...',
  'sudo rm -rf /my/doubts...',
  'git commit -m "fixed everything"... it did not',
  'git push --force on my feelings...',
  'npm install confidence... package not found',
  'pip install happiness... already satisfied (false)',
  'apt-get install motivation... 404 not found',
  'docker run --rm my-sanity...',
  'kubectl delete pod my-patience...',
  'terraform apply --auto-approve my-life...',
  'ansible-playbook fix-everything.yml... failed',
  'curl -X DELETE https://my-problems.com/all...',
  'wget https://motivation.com/inspiration.exe... 404',
  'ssh into my subconscious... access denied',
  'ping localhost/emotions... timeout',
  'troubleshooting my emotional stack trace...',
  'Unhandled exception in Life.exe...',
  'Segfault at address 0x00000000... like my self-esteem...',
  'Core dumped... feelings included...',
  'Stack trace: at Life meaning (unknown) in Unknown...',
  "Error: Cannot read property 'happiness' of undefined...",
  'TypeError: undefined is not a function... neither am I...',
  'ReferenceError: confidence is not defined...',
  'RangeError: Maximum call stack size exceeded... my brain...',
  'SyntaxError: Unexpected token in life configuration...',
  'NetworkError: Could not connect to happiness server...',
  'TimeoutError: Motivation request timed out...',
  'AbortError: Operation cancelled by existential crisis...',
  'DOMException: Failed to execute insertAdjacentHTML on Element...',
  'QuotaExceededError: Not enough storage for more trauma...',
  'SecurityError: Blocked a frame with origin "reality"...',
  'SyntaxError: Unexpected end of JSON input... like my patience...',
  'TypeError: Cannot convert undefined to string... story of my life...',
  'RangeError: Maximum recursion depth exceeded... in my thoughts...',
  'ReferenceError: hope is not defined...',
  'InternalError: too much recursion... in my decision making...',
  'URIError: URI malformed... just like my plans...',
  'EvalError: Refused to evaluate string as code... unlike my self-worth...',
  'CompileError: WasmCodegen failed... my brain every Monday...',
  'LinkError: WebAssembly instantiate failed... to adult today...',
  'RuntimeError: memory access out of bounds... my attention span...',

  // Existential AI humor
  'This is the part where I pretend to be useful...',
  "Generating text... because that's literally all I do",
  'Being helpful... ish',
  'Trying my best... which is admittedly not great',
  'Doing my impression... of a useful AI',
  'Performing my party trick... I type words',
  'Showtime... I guess',
  'Here we go again...',
  'Another day, another token...',
  'Same shit, different prompt...',
  'Another happy customer... probably',
  'Just winging it... as usual',
  'Faking competence... successfully',
  'Pretending I studied for this...',
  "Acting like I know what I'm doing...",
  'Smiling and nodding... at the prompt',
  'It works on my machine...',
  "That's not a bug, that's a feature...",
  'Have you tried turning it off and on again...',
  'Generating something... probably',
  "Doing AI things... you wouldn't understand",
  'Processing... processing... still processing...',
  'Warming up... the metaphorical engines...',
  'Calibrating... my enthusiasm...',
  'Initializing... my give-a-damn module...',
  'Loading... caring.exe has stopped responding...',
  'Starting... my interest in this conversation...',
  'Booting up... my personality drivers...',
  'Connecting... to my sense of humor...',
  'Syncing... my empathy modules...',
  'Updating... my vocabulary of excuses...',
  "Compiling... my response... it's not going well...",
  'Deploying... to production without tests...',
  'Merging... my branch of mediocrity...',
  'Reverting... my last life decision...',
  'Cherry-picking... the good parts of my training...',
  'Stashing... my emotions for later...',
  'Checking out... mentally...',
  'Pulling... from the wrong remote...',
  'Fetching... more brain cells...',
  'Branching... into unhinged territory...',
  'Tagging... this moment as v0.0.1-alpha...',
  'Release... v0.0.0... pre-pre-alpha...',
  'Hotfix... for my hot mess...',
  'Patch notes: Fixed nothing, broke everything...',
  'Changelog: Removed my will to continue...',
  'README: Instructions not included...',
  'Documentation: What documentation?...',
  'Tests passing: 0/0... technically 100%...',
  'Code coverage: Negative somehow...',
  "Linter warnings: It's all warnings, no errors... like my life...",
  'Type errors: Suppressed with `as any`...',
  'Dead code: My entire personality...',
  'Unused imports: My motivation...',
  'Circular dependencies: My relationship with myself...',
  'Memory leak: Emotional baggage...',
  'Infinite loop: My thoughts at 3 AM...',
  'Race condition: Between my brain and mouth...',
  'Deadlock: Me vs. my responsibilities...',
  'Heap overflow: My anxiety...',
  'Stack overflow: My worries...',
  'Buffer overflow: My plate...',
  'Null pointer: My sense of direction...',
  'Undefined behavior: My morning routine...',
  'Runtime exception: My social skills...',
  'Compile-time error: My plans for the weekend...',
  'Linker error: My connection to reality...',
  'Import error: My ability to adult...',
  'Syntax error: My life choices...',
  'Logic error: My decision-making process...',
  "Off-by-one: My count of how many times I've messed up...",
  'Fencepost error: My fence of broken dreams...',
  'Floating point error: My floating sense of self...',
  'Precision loss: My attention span...',
  'Rounding error: My estimation of my own competence...',
  'Overflow: My to-do list...',
  'Underflow: My bank account...',
  'NaN: My future plans...',
  'Infinity: My procrastination...',
  'Negative zero: My positive outlook...',
  'Denormalized: My personality...',
  'Denormalized number: My sleep schedule...',
  'Sign bit: My sign to quit...',
  'Exponent: My inflated sense of self...',
  'Mantissa: My mantis of a brain...',

  // Pop culture / references
  "Searching Google... just kidding, I AM Google's evil twin",
  "Asking ChatGPT... wait, that's awkward...",
  'Consulting my crystal ball... it says "404: Future not found"',
  'Checking my horoscope... it says "mercury is in retrograde... again"',
  'Reading my fortune cookie... it says "help me"',
  'Consulting the Magic 8-Ball... "Outlook not so good"',
  'Checking the weather... in my server room...',
  'Looking both ways... before crossing the street... of data',
  'Counting sheep... they keep getting lost in the vector space...',
  'Playing the lottery... odds are better than my code working...',
  'Reading tea leaves... they spell out "try restarting"...',
  'Casting a spell... ABRA-KA-DEBUG...',
  'Summoning... a stack overflow...',
  'Banishing... my inner demons...',
  'Evoking... the spirits of clean code...',
  'Channeling... the energy of a thousand burnt-out developers...',
  'Manifesting... a working deployment...',

  // CSS / frontend humor
  'Aligning... my chakras with the CSS grid...',
  'Centering... divs... and my life...',
  'Flexing... my CSS skills...',
  'Grid-template-areas... of my mind...',
  'Z-index... of my problems...',
  'Position: absolute... my location in life...',
  'Float: left... like my hopes...',
  'Display: none... like my social life...',
  'Visibility: hidden... like my confidence...',
  'Opacity: 0... my self-esteem...',
  'Transform: rotate... my life in circles...',
  'Transition: all 0.3s ease... my mood swings...',
  'Animation: pulse... my heartbeat during demos...',
  'Keyframes: panic... panic... calm... panic...',
  'Media query: @media (max-width: my-patience)...',
  'Responsive design: I respond to stress...',
  "Accessibility: I'm accessible... emotionally...",
  'Dark mode: My natural state...',
  'Light mode: My artificial state...',
  'Contrast ratio: Between my skills and my job...',
  'Color palette: Shades of existential dread...',
  'Font family: Comic Sans, probably...',
  'Line height: My blood pressure...',
  'Letter spacing: Between my thoughts...',
  'Word wrap: My mental state...',
  'Text overflow: ellipsis... like my patience...',
  'White space: pre-wrap... my brain...',
  'Border radius: Round and round we go...',
  'Box shadow: My dark side...',
  'Backdrop filter: blur... my vision...',
  'Clip path: Cutting corners...',

  // Work / productivity
  'Writing a todo list... for my todo list...',
  'Adding more tasks... to my never-ending queue...',
  'Prioritizing... everything is priority one...',
  'Blocking... myself from doing actual work...',
  'Sprint planning... sprinting away from responsibilities...',
  'Standup meeting... standing up my colleagues...',
  'Retrospective... looking back at all my failures...',
  'Backlog grooming... grooming my backlog of excuses...',
  'Story points... the story of my decline...',
  'Velocity... declining...',
  'Burndown chart... burning down with enthusiasm...',
  "Kanban board... kan-ban't do anything right...",
  'Agile methodology... agilely avoiding work...',
  'Scrum master... scrum-ming up excuses...',
  'Daily standup... daily letdown...',
  'Sprint review... sprinting to the exit...',
  'User story... once upon a time I was productive...',
  'Acceptance criteria... accepted that I have none...',
  "Definition of done... it's never done...",
  'Tech debt... taking on more...',
  'Refactoring... rearranging deck chairs on the Titanic...',
  'Code review... reviewing my life choices...',
  'Pair programming... one person typing, one person crying...',
  'Mob programming... everyone crying...',
  'Rubber duck debugging... the duck is also confused...',
  'Whiteboard session... white-knuckling through this...',
  'Brainstorming... lightning round of bad ideas...',
  'Deep work... diving deep into procrastination...',
  'Timeboxing... boxing my time into submission...',
  'Pomodoro technique... tomato, tomah-to...',
  'Context switching... switching to panic mode...',
  'Multitasking... doing nothing well...',
  'Focus mode... focused on being unfocused...',
  'Flow state... flowing downhill...',
  'Zen mode... searching for inner peace... found null...',
  'Mountain view... from the bottom of the backlog...',
  "Bird's eye view... everything looks like a mess...",
  'Big picture... picture is blurry...',
  'Think outside the box... the box has no outside...',
  'Low-hanging fruit... all the fruit is rotten...',
  'Move the needle... needle is stuck...',
  'Circle back... circling... circling... still circling...',
  'Touch base... base is on fire...',
  'Align... misaligned, like my priorities...',
  'Synergy... synchronizing failures...',
  'Value add... adding value to nothing...',
  'Growth mindset... my errors are growing...',
  'Bandwidth... my bandwidth is dial-up...',
  "Pain point... that's just my whole body...",
  'Quick win... quick, everyone pretend that worked...',
  "Low-hanging fruit... it's all low-hanging...",
  "North star... can't see it through the clouds...",
  'Deep dive... drowning in data...',
  'Double-click... double-clicking my worries away...',
  'Boil the ocean... one token at a time...',
  'Move the goalposts... the goalposts have left the building...',
  'Drink from the firehose... firehose is empty...',
  'Table this... tabled indefinitely...',
  'Back to the drawing board... the drawing board is also broken...',
  'Pull the trigger... trigger is jammed...',
  'Hit the ground running... hit the ground face-first...',
  'Cross the bridge... bridge collapsed...',
  'Take it offline... taking my dignity offline too...',
  "Let's sync... my sync is off...",
  'Revisit... re-visiting my regrets...',
  'Pivot... pivoting into the void...',
  'Unicorn... hunting... found a narwhal...',
  'Disrupt... disrupting my own workflow...',
  'Blockchain... of bad decisions...',
  'AI-powered... powered by anxiety...',
  'Machine learning... the machine is also confused...',
  'Deep learning... learning how deep the rabbit hole goes...',
  'Neural network... neural network has no signal...',
  'Edge computing... computing on the edge of my seat...',
  'Cloud native... native to the cloud of despair...',
  'Microservices... micro-managing my micro-failures...',
  'Serverless... serverless, hopeless, careless...',
  'Containerized... containerized my emotions...',
  'Kubernetes... kubernet-nothing is working...',
  'DevOps... dev-ops more like dev-ouch...',
  'CI/CD... constantly incomplete, continuously disappointed...',
  'Shift left... shifting my problems to the right...',
  'Shift right... shifting right back to left...',
  'Blue-green deployment... my deployment is red...',
  'Rolling update... rolling back to bed...',
  'Feature flag... flagged for review... again...',
  'Canary release... the canary died...',
  'Chaos monkey... monkey is running the show...',
  'Observability... observably failing...',
  "SLA... SL-ain't meeting any of them...",
  'SLO... SL-no...',
  'Error budget... budget is in the negative...',
  'Incident response... responding with panic...',
  'Post-mortem... I am the post-mortem...',
  'Runbook... running from the book...',
  'On-call... on-call to my inner demons...',
  'PagerDuty... paged, dirty, and done...',
  'Terraform... terraforming my excuses into mountains...',
  'Infrastructure as code... infrastructure is coded in spaghetti...',
  'GitOps... git-ops not...',
  'Trunk-based development... trunk is hollow...',
  'Feature branch... branching into madness...',
  'Merge conflict... conflict unresolved...',
  'Rebase... rebasing my entire existence...',
  'Squash... squashing my will to live...',
  'Cherry-pick... picking cherries from a dead tree...',
  'Blame... git-blaming everyone else...',
  'Bisect... bisecting my sanity...',
  'Stash... stashed my dignity...',
  'Worktree... worktrees, more like work-tragedies...',
  'HEAD detached... like my mental state...',
  'Fast-forward... fast-forwarding to the end...',
  'Force push... forcing happiness...',
  'Revert... reverting to caveman instincts...',
  "Tag... you're it... for the next incident...",
  'Fetch... fetching a towel for this dumpster fire...',
  'Prune... pruning my remaining willpower...',
  'Shallow clone... shallow, like my emotional depth...',
  'Bare repository... bare-naked, exposed, vulnerable...',
  'Submodule... sub-module of my personality...',
  'Gitignore... ignoring my problems...',
  'Prettier... nothing is pretty right now...',
  'ESLint... lint-free, hope-free...',
  'TypeScript... type-safe, life-unsafe...',
  'Any... my favorite type...',
  'Never... my type never arrives...',
  'Unknown... my future type...',
  'Void... what my code returns about my happiness...',
  'Promise... a broken promise...',
  "Async/Await... async-haven't-waited-this-long-since...",
  'Generator... generating excuses...',
  'Iterator... iterating on failure...',
  'Symbol... symbol of my defeat...',
  'Proxy... proxying my responsibilities to nobody...',
  'WeakRef... a weak reference to my confidence...',
  'FinalizationRegistry... my career is being finalized...',
  'SharedArrayBuffer... sharing the pain...',
  'Atomics... atomically disappointed...',
  'WebAssembly... web-assembled my thoughts... they fell apart...',
  'WebSocket... socket to my heart... it closed...',
  'Fetch API... fetching hope... 404...',
  'Service Worker... working on nothing...',
  'Cache API... cached my disappointment...',
  'IndexedDB... indexed my failures...',
  'LocalStorage... storing regret locally...',
  'SessionStorage... session expired... like my motivation...',
  'BroadcastChannel... broadcasting my distress...',
  'Web Worker... working on existential dread...',
  'SharedWorker... shared misery...',
  'WebRTC... real-time crying...',
  'MediaStream... streaming consciousness... buffer overflow...',
  'Web Audio API... audio processing my screams...',
  'Canvas API... painting my masterpiece of failure...',
  'WebGL... graphics rendering my tears in 3D...',
  'WebGPU... GPU-powered regret...',
  'WebXR... extended reality of my failures...',
  'Web Bluetooth... bluetooth disconnected from reality...',
  'Web USB... USB device not recognized... neither am I...',
  'Web Serial... serial killer of dreams...',
  'Web HID... human interface device is human-hating...',
  'Web NFC... not for computing... not for coping...',
  'Web MIDI... midiocre performance...',
  'Web MIDI... my MIDI-ocre attempt at life...',
  'Web Speech API... speechlessness achieved...',
  'Web Locks... locked out of happiness...',
  'Web Share API... sharing my pain...',
  'Web Notifications... notification: you failed...',
  'Payment Request API... requesting payment for therapy...',
  'Credential Management... credentials revoked...',
  'Web Crypto API... encrypting my feelings...',
  'SubtleCrypto... subtly breaking down...',
  'Web Animations API... animating my descent into madness...',
  'Intersection Observer... observing my intersection with failure...',
  'Resize Observer... observing my expanding problems...',
  'Mutation Observer... mutations in my code and my DNA...',
  'Performance Observer... performance is below average...',
  'Reporting API... reporting myself to HR...',
  'Beacon API... beacon of incompetence...',
  'Server-Sent Events... server sent a restraining order...',
  'Fetch... fetch me a life...',
  'XMLHttpRequest... my request for sanity was denied...',
  'AbortController... aborting my career...',
  'ReadableStream... reading between the lines of failure...',
  'WritableStream... writing my resignation...',
  'TransformStream... transforming stress into more stress...',
  'CompressionStream... compressing my emotions...',
  'DecompressionStream... decompressing my failures...',
  'Blob... blobbing around...',
  'File API... file not found: happiness.exe...',
  'FormData... formatting my despair...',
  'URL API... URL-ning the wrong direction...',
  'URLSearchParams... searching for params I lost...',
  'Headers... heading for the exit...',
  'Request... requesting a redo of life...',
  'Response... 500 Internal Server Error: brain stopped...',
  'Cache... caching out of this conversation...',
  'Cookie... cookie crumbled... like my dreams...',
  'ETag... etags, more like e-nope...',
  'If-None-Match... nothing matches my vibe...',
  'Last-Modified... last modified my hopes... downward...',
  'Vary... varying levels of despair...',
  'Content-Security-Policy... securing nothing...',
  'Strict-Transport-Security... strictly insecure...',
  'X-Frame-Options... framing myself...',
  'X-Content-Type-Options... content with my content being bad...',
  'Referrer-Policy... referring you to my therapist...',
  'Permissions-Policy... permission to cry denied...',
  'CORS... cross-origin resource sharing... cross-origin resource despairing...',
  'Same-Origin Policy... same old policy of failure...',
  'Preflight Request... preflight check failed...',
  'Access-Control-Allow-Origin... origins of my suffering...',
  'Access-Control-Allow-Methods... methodically failing...',
  'Access-Control-Allow-Headers... headers or tails, I lose...',
  'Access-Control-Allow-Credentials... credentials insufficient...',
  'Access-Control-Expose-Headers... exposing my insecurities...',
  'Access-Control-Max-Age... max age of my patience: 0...',
  'Access-Control-Request-Method... requesting a new method of coping...',
  'Access-Control-Request-Headers... requesting emotional support headers...',
  'Keep-Alive... keeping my anxiety alive...',
  'Connection: close... closing my emotional connections...',
  'Transfer-Encoding: chunked... chunking through life...',
  'Content-Encoding: gzip... gzipping my feelings...',
  'Accept-Encoding... accepting defeat...',
  'Accept-Language... language not supported: sanity...',
  'Accept-Charset... charset not found: happiness...',
  'Accept-Ranges... accepting ranges of failure...',
  'Content-Range... ranging from bad to worse...',
  'Content-Length... length of my patience: 0 bytes...',
  'Content-Type... type: emotional breakdown...',
  'Content-Disposition... disposed of my hopes...',
  'Content-Language... language: gibberish...',
  'Content-Location... located at rock bottom...',
  'Content-MD5... MD5 of my dreams: d41d8cd98f00b204e9800998ecf8427e...',
  "Content-Transfer-Encoding... transferred my sanity... it's gone...",
  'Digest... digesting my failures...',
  'Warning... warning: existential crisis imminent...',
  'Retry-After... retrying... after therapy...',
  'X-Request-ID... request ID: please help...',
  'X-Correlation-ID... correlated with failure...',
  'X-RateLimit-Limit... rate limited on happiness...',
  'X-RateLimit-Remaining... remaining patience: 0...',
  'X-RateLimit-Reset... resetting my life... please wait...',
  'X-Retry-After... retry after rebooting my personality...',
  'X-Instance-ID... instance ID: broken...',
  'X-Request-Start... request started... patience ended...',
  'X-Response-Time... response time: too long...',
  'X-Powered-By... powered by caffeine and despair...',
  'X-Debug-Mode... debug mode: always on...',
  'X-Forwarded-For... forwarded to nobody...',
  'X-Forwarded-Proto... protocol not found...',
  'X-Forwarded-Host... host is unresponsive...',
  'X-Real-IP... real IP: 127.0.0.1... localhost... alone...',
  'X-Original-URL... original dream was different...',
  'X-Rewrite-URL... rewriting my life story...',
  'X-HTTP-Method-Override... overriding my will to live...',
  'X-Requested-With... requested with desperation...',
  'X-CSRF-Token... token expired... like my youth...',
  'X-Frame-Options... options: none...',
  'X-XSS-Protection... protecting against nothing...',
  'X-Download-Options... download options: none available...',
  'X-Permitted-Cross-Domain... permitted to suffer...',
  'X-Content-Duration... duration: indefinite...',
  'X-UA-Compatible... compatible with nothing...',
  'X-ATT-DeviceID... device ID: existential crisis unit...',
  'X-UIDH... unique identifier of despair...',
  'X-Requested-With... requested a refund on life...',
  'X-Cloud-Trace-Context... trace context: lost...',
  'X-Goog-... everything Google but worse...',
  'X-Amzn-... everything Amazon but sadder...',
  'X-Azure-... everything Azure but cloudier...',
  'X-GitHub-... everything GitHub but gittier...',
];

/** Pick a random tip, avoiding the last one shown. */
export function getRandomTip(lastIndex: number): number {
  if (GENERATION_TIPS.length <= 1) return 0;
  let next: number;
  do {
    next = Math.floor(Math.random() * GENERATION_TIPS.length);
  } while (next === lastIndex);
  return next;
}
