export const SHARED_CONST = {
  SECRET_KEYS: [
    'libre_url',
    'lingva_url',
    'oneringtranslator_url',
    'deeplx_url',
    'deepl_key',
    'google_translate_key',
    'yandex_translate_key',
    'bing_translate_key',
    'serpapi_key',
    'searxng_url',
    'tavily_key',
    'open_router_key',
    'cohere_key',
    'ai21_key',
    'xai_key',
    'azure_openai_key',
    'groq_key',
    'koboldcpp_key',
    'openai_key',
    'makersuite_key',
    'vertexai_key',
    'mistralai_key',
    'deepseek_key',
    'aimlapi_key',
    'fireworks_key',
    'claude_key',
    'chutes_key',
    'electronhub_key',
    'nanogpt_key',
    'cometapi_key',
    'moonshot_key',
    'zai_key',
    'siliconflow_key',
    'minimax_key',
    'open_router_model',
    'cohere_model',
    'ai21_model',
    'xai_model',
    'azure_openai_model',
    'groq_model',
    'koboldcpp_model',
    'openai_model',
    'makersuite_model',
    'vertexai_model',
    'mistralai_model',
    'deepseek_model',
    'aimlapi_model',
    'fireworks_model',
    'claude_model',
    'chutes_model',
    'electronhub_model',
    'nanogpt_model',
    'cometapi_model',
    'moonshot_model',
    'zai_model',
    'siliconflow_model',
    'minimax_model',
    'koboldai_url',
    'koboldai_key',
    'koboldai_model',
    'ollama_url',
    'ollama_key',
    'ollama_model',
    'tabby_url',
    'tabby_key',
    'tabby_model',
    'text_generation_webui_url',
    'text_generation_webui_key',
    'ooba_url',
    'ooba_key',
    'aphrodite_url',
    'aphrodite_key',
    'llamacpp_url',
    'llamacpp_key',
    'stable_diffusion_url',
    'comfy_url',
    'comfyrunpod_key',
    'together_key',
    'sdcpp_url',
    'drawthings_url',
    'pollinations_url',
    'stability_key',
    'huggingface_key',
    'bfl_key',
    'falai_key',
    'workersai_key',
    'elevenlabs_key',
  ] as const,

  CHAT_COMPLETION_SOURCES: [
    'openai',
    'openrouter',
    'custom',
    'cohere',
    'ai21',
    'xai',
    'azure_openai',
    'groq',
    'koboldcpp',
    'openai_legacy',
    'makersuite',
    'vertexai',
    'mistralai',
    'deepseek',
    'aimlapi',
    'fireworks',
    'claude',
    'chutes',
    'electronhub',
    'nanogpt',
    'cometapi',
    'moonshot',
    'zai',
    'siliconflow',
    'minimax',
    'ollama',
  ] as const,

  TEXT_COMPLETION_SOURCES: [
    'kobold',
    'textgenerationwebui',
    'ooba',
    'aphrodite',
    'llamacpp',
    'ollama',
    'tabby',
    'mancer',
    'vllm',
    'openrouter',
    'featherless',
    'huggingface',
    'dreamgen',
    'togetherai',
    'infermaticai',
    'generic',
  ] as const,

  PRESET_CATEGORIES: [
    'openai',
    'kobold',
    'koboldhorde',
    'novel',
    'textgenerationwebui',
    'instruct',
    'context',
    'sysprompt',
    'reasoning',
    'generation',
  ] as const,

  EXPORTABLE_SECRET_KEYS: [
    'libre_url',
    'lingva_url',
    'oneringtranslator_url',
    'deeplx_url',
    'searxng_url',
  ] as const,

  AVATAR_WIDTH: 400,
  AVATAR_HEIGHT: 600,
  DEFAULT_AVATAR_PATH: 'data/default-user/characters/placeholder.png',
  SESSION_COOKIE_NAME: 'WorldCore-session',
  API_VERSION_PREFIX: '/api/v1',
} as const;
