import { z } from 'zod';
import { ReasoningSettingsSchema } from './reasoning';

export const SyspromptSettingsSchema = z.object({
  enabled: z.boolean(),
  selectedPreset: z.string(),
  content: z.string(),
  postHistoryInstructions: z.string(),
});

export const ContextSettingsSchema = z.object({
  selectedPreset: z.string(),
  storyString: z.string(),
  chatStart: z.string(),
  exampleSeparator: z.string(),
  storyStringPosition: z.enum(['default', 'inchat']),
  storyStringDepth: z.number().int().min(0),
  storyStringRole: z.enum(['system', 'user', 'assistant']),
  forceName2: z.boolean(),
  singleLine: z.boolean(),
  collapseNewlines: z.boolean(),
  trimSpaces: z.boolean(),
  trimSentences: z.boolean(),
  separatorsAsStopStrings: z.boolean(),
  namesAsStopStrings: z.boolean(),
});

export const InstructSettingsSchema = z.object({
  enabled: z.boolean(),
  selectedPreset: z.string(),
  storyStringPrefix: z.string(),
  storyStringSuffix: z.string(),
  inputSequence: z.string(),
  inputSuffix: z.string(),
  outputSequence: z.string(),
  outputSuffix: z.string(),
  systemSequence: z.string(),
  systemSuffix: z.string(),
  firstOutputSequence: z.string(),
  lastOutputSequence: z.string(),
  firstInputSequence: z.string(),
  lastInputSequence: z.string(),
  lastSystemSequence: z.string(),
  stopSequence: z.string(),
  userAlignmentMessage: z.string(),
  wrap: z.boolean(),
  macro: z.boolean(),
  sequencesAsStopStrings: z.boolean(),
  skipExamples: z.boolean(),
  namesBehavior: z.enum(['none', 'force', 'always']),
  activationRegex: z.string(),
  bindToContext: z.boolean(),
  systemPrompt: z.string(),
  separatorSequence: z.string(),
  systemSequencePrefix: z.string(),
  systemSequenceSuffix: z.string(),
  names: z.boolean(),
  namesForceGroups: z.boolean(),
  systemSameAsUser: z.boolean(),
});

export const TextOptionsSchema = z.object({
  sysprompt: SyspromptSettingsSchema,
  context: ContextSettingsSchema,
  instruct: InstructSettingsSchema,
  stoppingStrings: z.string(),
  tokenizer: z.string(),
  tokenPadding: z.number().int().min(0),
  reasoning: ReasoningSettingsSchema,
  bindModelTemplates: z.boolean(),
  markdownEscapeStrings: z.string(),
  startReplyWith: z.string(),
  showReplyPrefix: z.boolean(),
});

export const TextOptionsDefaults: z.infer<typeof TextOptionsSchema> = {
  sysprompt: {
    enabled: true,
    selectedPreset: 'Neutral - Chat',
    content: "Write {{char}}'s next reply in a fictional chat between {{char}} and {{user}}.",
    postHistoryInstructions: '',
  },
  context: {
    selectedPreset: 'Default',
    storyString:
      "{{#if system}}{{system}}\n{{/if}}{{#if description}}{{description}}\n{{/if}}{{#if personality}}{{char}}'s personality: {{personality}}\n{{/if}}{{#if scenario}}Scenario: {{scenario}}\n{{/if}}{{#if persona}}{{persona}}\n{{/if}}",
    chatStart: '***',
    exampleSeparator: '***',
    storyStringPosition: 'default',
    storyStringDepth: 1,
    storyStringRole: 'system',
    forceName2: true,
    singleLine: false,
    collapseNewlines: false,
    trimSpaces: true,
    trimSentences: false,
    separatorsAsStopStrings: true,
    namesAsStopStrings: true,
  },
  instruct: {
    enabled: false,
    selectedPreset: 'Alpaca',
    storyStringPrefix: '',
    storyStringSuffix: '',
    inputSequence: '### Instruction:',
    inputSuffix: '',
    outputSequence: '### Response:',
    outputSuffix: '',
    systemSequence: '',
    systemSuffix: '',
    firstOutputSequence: '',
    lastOutputSequence: '',
    firstInputSequence: '',
    lastInputSequence: '',
    lastSystemSequence: '',
    stopSequence: '',
    userAlignmentMessage: '',
    wrap: true,
    macro: true,
    sequencesAsStopStrings: true,
    skipExamples: false,
    namesBehavior: 'force',
    activationRegex: '',
    bindToContext: false,
    systemPrompt: '',
    separatorSequence: '',
    systemSequencePrefix: '',
    systemSequenceSuffix: '',
    names: false,
    namesForceGroups: false,
    systemSameAsUser: false,
  },
  stoppingStrings: '[]',
  tokenizer: 'best',
  tokenPadding: 64,
  reasoning: {
    selectedPreset: 'Default',
    prefix: '<think>',
    suffix: '</think>',
    separator: '\n',
    autoParse: false,
    autoExpand: false,
    showHidden: true,
    addToPrompts: false,
    maxAdditions: 1,
  },
  bindModelTemplates: false,
  markdownEscapeStrings: '',
  startReplyWith: '',
  showReplyPrefix: true,
};

export function mergeTextOptions(
  partial?: Partial<z.infer<typeof TextOptionsSchema>>,
): z.infer<typeof TextOptionsSchema> {
  return {
    ...TextOptionsDefaults,
    ...partial,
    sysprompt: { ...TextOptionsDefaults.sysprompt, ...partial?.sysprompt },
    context: { ...TextOptionsDefaults.context, ...partial?.context },
    instruct: { ...TextOptionsDefaults.instruct, ...partial?.instruct },
    reasoning: { ...TextOptionsDefaults.reasoning, ...partial?.reasoning },
  };
}
